if(UNIX)
    execute_process(COMMAND "${CMAKE_SOURCE_DIR}/get_git_timestamp.sh" OUTPUT_VARIABLE GIT_TIMESTAMP)
elseif(WIN32)
    execute_process(COMMAND "${CMAKE_SOURCE_DIR}\\get_git_timestamp.bat" OUTPUT_VARIABLE GIT_TIMESTAMP)
else()
    set(GIT_TIMESTAMP "UNKNOWN")
endif()
string(REPLACE "\n" ""  GIT_TIMESTAMP ${GIT_TIMESTAMP} )
message(STATUS "Current git timestamp is ${GIT_TIMESTAMP}\n")
set(CPACK_PACKAGE_VERSION ${GIT_TIMESTAMP})
